network:
  version: 2
  renderer: networkd
  ethernets:
# We want to add 'optional: true' to each of the interfaces.
# Otherwise, the system will take two additional minutes to
# boot, and that's just annoying.
    enp1s0:
      optional: true
      dhcp4: true
    enp2s0:
      optional: true
      dhcp4: true
    enp3s0:
      optional: true
      dhcp4: true
    enp4s0:
      optional: true
      dhcp4: true
    enp5s0:
      optional: true
      dhcp4: true
    enp6s0:
      optional: true
      dhcp4: false
